models:
  - name: gpt-3.5-turbo
    providers: [OpenAI, DeepSeek, Custom]
    max_tokens: 1000
    temperature: 0.7
  - name: gpt-4
    providers: [OpenAI, DeepSeek, Custom]
    max_tokens: 1000
    temperature: 0.7
  - name: deepseek-chat
    providers: [DeepSeek, Custom]
    max_tokens: 1000
    temperature: 0.7